Fix page_detail bug.
Add new bug: jinja2.exceptions.UndefinedError: 'game.User object' has no attribute 'age'

This is because it is trying to sort User by age .. instead of hero by age.