Implement hero.current_city and hero.current_location
Instead of world_map.current_location etc.
Build a test case for current_city as well.
Found some bugs:
hero object doesn't neccessarily save during database.update()
Unless added to session?

And database.update() during logout causes:
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: Attempting to flush an item of type <class 'items.Quest_Item'> as a member of collection "Hero.inventory". Expected an object of type <class 'items.Item'> or a polymorphic subclass of this type. If <class 'items.Quest_Item'> is a subclass of <class 'items.Item'>, configure mapper "Mapper|Item|items" to load this subtype polymorphically, or set enable_typechecks=False to allow any subtype to be accepted for flush.
I added a tonne of issues to github about most of that so I will start pushing that forward next.